site_name: fastapi-orbit
site_url: https://fastapi-orbit.gabover.se
repo_url: https://github.com/gaboverse/fastapi-orbit
repo_name: gaboverse/fastapi-orbit
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  palette: 
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  logo: assets/img/fastapi-orbit-isotype.png
  favicon: assets/img/fastapi-orbit-isotype.png
extra_css:
  - stylesheets/extra.css
nav:
  - fastapi-orbit: index.md
